openapi: 3.0.1
info:
  title: Management of the Cinema API
  version: 1.0.1
  description: "Hello every body, this is the management of the cinema projection"
servers:
  - url: https://RoomsMovies.com
tags:
  - name: Rooms
  - name: Films
  - name: Projections
paths:
  /rooms:
    get:
      tags:
        - "Rooms"
      summary: Get all Rooms
      operationId: getRooms
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"
        400:
          description: Error
          content: {}
  /rooms/{id}:
    get:
      tags:
        - "Rooms"
      summary: get the room by specified id
      operationId: getRoom
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Room"
  /films:
    get:
      tags:
        - "Films"
      summary: Get all Films
      operationId: getFilms
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Film"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Films"
      summary: modifies entirely a film list
      requestBody:
        description: new film
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/NewFilm"
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Film"
        400:
          description: Error
          content: {}

  /film/{id}:
    get:
      tags:
        - "Films"
      summary: get the film by specified id
      operationId: getFilm
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Films"
      summary: allows you to modify film data except its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        description: new film
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewFilm"
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Film"
        400:
          description: Error
          content: {}
    delete:
      tags:
        - "Films"
      summary: deletes a film by referring to its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: "Returns the id of the deleted student"

        400:
          description: Error
          content: {}
  /film/category:
    get:
      tags:
        - Films
      summary: Select films by category
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
          examples:
            changeFilm:
              summary: Change categories
              value:
                filmcategorie: drame
      responses:
        200:
          description: List of films
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Film"
        400:
          description: Bad request
          content: {}
  /projections:
    get:
      tags:
        - "Projections"
      summary: Get all projections
      operationId: getProjections
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Projections"
      summary: modifies entirely a Projection list
      requestBody:
        description: new film
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                allOf:
                  - $ref: "#/components/schemas/NewProjection"
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    post:
      tags:
        - "Projections"
      summary: creates a new Projection
      requestBody:
        required: true
        description: new film
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProjection"
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    patch:
      tags:
        - "Projections"
      description: |
        Possible changes on:
        * film: change
        * room: change
        * time: change time
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Projection"
            examples:
              changeFilm:
                summary: Change some films
                value:
                  - id: 1
                    filmId: 1
                  - id: 2
                    filmId: 2
              changeRoom:
                summary: Change room
                value:
                  - id: 1
                    roomId: B
                  - id: 2
                    roomId: B
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Projection"
  /projection/{id}:
    get:
      tags:
        - "Projections"
      summary: get the projection by specified id
      operationId: getProjection
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    put:
      tags:
        - "Projections"
      summary: allows you to modify projection data except its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        description: new projection
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              allOf:
                - $ref: "#/components/schemas/NewProjection"
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projection"
        400:
          description: Error
          content: {}
    delete:
      tags:
        - "Projections"
      summary: deletes a projection by referring to its id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Returns the id of the deleted projection"

        400:
          description: Error
          content: {}
  /projection/category:
    get:
      tags:
        - Projections
      summary: Select films projectionDate by category
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of films
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Categories"
        400:
          description: Bad request
          content: {}
  /projections/Week_Programs:
    get:
      tags:
        - "Projections"
      summary: Get all projection next week
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
      operationId: get_Next_Week_Projections
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: "2"
                  projectionDate:
                    type: string
                    format: date-time
                    example: 2022-08-07T13:12:17.999Z
                  film:
                    $ref: "#/components/schemas/Film"
                  room:
                    $ref: "#/components/schemas/Room"
                  400:
                    description: Error
components:
  schemas:
    Room:
      type: object
      properties:
        id:
          type: string
          example: "A"
        capacity:
          type: integer
          example: 50

    NewFilm:
      type: object
      properties:
        title:
          type: string
          example: Mission impossible
        duration:
          type: string
          example: 2h
        director:
          type: string
          example: Frank
        date:
          type: string
          format: date
          example: 2022-08-06
    Film:
      type: object
      properties:
        id:
          type: integer
          example: 5
      allOf:
        - $ref: "#/components/schemas/NewFilm"
    NewProjection:
      type: object
      properties:
        filmId:
          type: integer
          example: 3
        roomId:
          type: string
          default: A
          enum:
            - A
            - B
        projectionDate:
          type: string
          format: date-time
    Projection:
      type: object
      properties:
        id:
          type: number
          example: "1"
        projectionDate:
          type: string
          format: date-time
        film:
          $ref: "#/components/schemas/Film"
        room:
          $ref: "#/components/schemas/Room"
    NewCategories:
      type: object
      properties:
        type:
          type: string
          example: drame
    Categories:
      allOf:
        - $ref: "#/components/schemas/NewCategories"
      type: object
      properties:
        id:
          type: integer
          example: 2
